DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;
USE burger_db;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	devour BOOLEAN DEFAULT false,
	description VARCHAR(255),
	createdAt TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);
